### ISSUE TITLE
有没有群一类的？

### ISSUE THREAD

**Issue by wudifeixue** [dd-center/vtbs.moe#11]
不少乱七八糟的小问题想问，但是感觉不停的开issue又不太合适？

**Comment by simon300000** [comment]
木有→_→

**Comment by simon300000** [comment]
我个人不太在意开issue问问题，没事的问吧233

**Comment by wudifeixue** [comment]
噗，开一个呀gkd，不过那我就不在issue上节制了

**Comment by simon300000** [comment]
不用节制（滑稽
我也不怎么用QQ来着

**Comment by simon300000** [comment]
@wudifeixue @3Shain @imlonghao @fzxiao233 @TomoeMami
我建了一个群:
欢迎加入GitHub DD CENTER，群聊号码: 663606562

**Comment by darkflame0** [comment]
@simon300000 这个群现在已经不让进来了吗=_=

**Comment by darkflame0** [comment]
@simon300000 这个群现在已经不让进了吗=_=

**Comment by simon300000** [comment]
> @simon300000 这个群现在已经不让进了吗=_=

嗯，现在改为邀请了

**Comment by darkflame0** [comment]
> > @simon300000 这个群现在已经不让进了吗=_=
> 
> 嗯，现在改为邀请了

那我可以申请进去吗？有想交流的还有想求助的事

**Comment by darkflame0** [comment]
> > @simon300000 这个群现在已经不让进了吗=_=
> 
> 嗯，现在改为邀请了

我能不能进呢……有点想交流求助的，有空的话也能帮忙做点东西什么的

**Comment by MiracleXYZ** [comment]
> > > @simon300000 这个群现在已经不让进了吗=_=
> > 
> > 
> > 嗯，现在改为邀请了
> 
> 我能不能进呢……有点想交流求助的，有空的话也能帮忙做点东西什么的

我看下能不能把你邀请进去~具体的我给你发邮件了

**Comment by Alexadnar** [comment]
> > > > @simon300000 这个群现在已经不让进了吗=_=
> > > 
> > > 
> > > 嗯，现在改为邀请了
> > 
> > 
> > 我能不能进呢……有点想交流求助的，有空的话也能帮忙做点东西什么的
> 
> 我看下能不能把你邀请进去~具体的我给你发邮件了

能麻烦拉下我么？？想为项目做做贡献。。

**Comment by TheSmileCat** [comment]
> > > > @simon300000 这个群现在已经不让进了吗=_=
> > > 
> > > 
> > > 嗯，现在改为邀请了
> > 
> > 
> > 我能不能进呢……有点想交流求助的，有空的话也能帮忙做点东西什么的
> 
> 我看下能不能把你邀请进去~具体的我给你发邮件了

请问我可以加一下吗？我想要修改一下VTBS的Java项目，找了一圈好像就[DDatJava](https://github.com/dd-center/DDatJava)是Java项目了
比如打包成API什么的
我想修改并依靠这个项目做点应用……例如SpringBoot/JavaEE或Maria机器人啥的
