### ISSUE TITLE
添加播放量日增数据和榜

### ISSUE THREAD

**Issue by wudifeixue** [dd-center/vtbs.moe#114]
关注榜固然重要，但是播放量也是非常关键的信息，现在是流量时代，能看到为何东西播放量增加太关键了。然后，能弄明白播放量和关注的日增也是非常关键的信息。

**Comment by simon300000** [comment]
随着榜单越来越多，我在想怎么样可以让navbar看起来不是那么长
可能需要弄一个二级目录

**Comment by wudifeixue** [comment]
可以合并急上升和急下降，点击第二次切换？

**Comment by wudifeixue** [comment]
播放量接口寄了
