### ISSUE TITLE
VTB补——特别类型的...就都加了吧

### ISSUE THREAD

**Issue by wudifeixue** [dd-center/vtbs.moe#116]
这里写上个人空间连接就行了
MeAqua动画制作委员会
https://space.bilibili.com/4307809
夏色まつり工坊
https://space.bilibili.com/418124907
诗音的魔法交流协会
https://space.bilibili.com/17384147
吹雪的猫咪茶铺
https://space.bilibili.com/431210892
澪雀之森的神社：
https://space.bilibili.com/3735586
大空家的荞麦面馆：
https://space.bilibili.com/476869039

**Comment by wudifeixue** [comment]
顺便再加一个彩虹新人，第一天同接3万的魔王
https://space.bilibili.com/2031109

**Comment by simon300000** [comment]
wow

**Comment by wudifeixue** [comment]
再来一个彩虹新人
星川Sara
https://space.bilibili.com/410542957

**Comment by user670** [comment]
1楼这几个链接到底是算不算vtuber？看上去像是其他vtuber的非官方衍生内容创作小组

**Comment by simon300000** [comment]
我在想一个办法可以区分这两种用户

**Comment by wudifeixue** [comment]
@user670 一楼这几个都是同人组，不算是vtuber
