### ISSUE TITLE
好像有的vtuber直播时人气一直显示0

### ISSUE THREAD

**Issue by EricJiangJiang** [dd-center/vtbs.moe#122]
比如花丸晴琉

**Comment by simon300000** [comment]
似乎是我的锅，可能是tcp连接有时候坏了不会被检测到
我重构了一下直播转发，不知道有没有修好
https://github.com/dd-center/bilibili-vtuber-live-danmaku-relay/commit/b8ad91e2e596b8813005aecff7bc8212d40b931b

并没有重构可能导致问题的部分，现在暂时修好了只是因为我重启了一下（

**Comment by EricJiangJiang** [comment]
ok, 谢谢大佬

**Comment by simon300000** [comment]
![D923AA67-F56C-4CE0-8405-36AF40938902](https://user-images.githubusercontent.com/12656264/69350088-34861500-0c79-11ea-9a2d-c7f5390e0bbd.png)
还有问题，我可能已经猜到是什么问题了，我今晚回去再修一次

**Comment by simon300000** [comment]
应该解决了
