### ISSUE TITLE
mutex mutex mutex

### ISSUE THREAD

**Issue by simon300000** [dd-center/vtbs.moe#129]

**Comment by Shigma** [comment]
草草草
你这是在说啥啊

**Comment by simon300000** [comment]
mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex

**Comment by 8MiYile** [comment]
你这说的是啥啊...

**Comment by simon300000** [comment]
mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex
mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex mutex

**Comment by Neteraxe** [comment]
今天刚好学到互斥锁……网页也需要这个嘛，代码果然是共通的

**Comment by simon300000** [comment]
看情况吧，如果有需求的话

Simon
simon30002021@icloud.com

**Comment by Neteraxe** [comment]
估计是代码优化的一部分了
在Android里，优化是很了不起的一件事，像QQ运行时占1G内存，都已经是优化后的结果了，毕竟Android是基于Linux系统改进的

**Comment by simon300000** [comment]
咦，不是为了防止多个来源同时访问同一个数据造成问题吗

Simon
simon30002021@icloud.com

**Comment by Neteraxe** [comment]
在Java中可以用synchronized，这个会自动解锁上锁，只是操作上有性能问题，不过作者看起来像是苹果党

**Comment by simon300000** [comment]
哦耶 完全忘自己在说什么，所以close 🎉
