### ISSUE TITLE
更好的过滤查找功能

### ISSUE THREAD

**Issue by simon300000** [dd-center/vtbs.moe#14]
借鉴→_→
https://graueneko.github.io/akhrchars.html

**Comment by wudifeixue** [comment]
感觉这个功能，还是蛮重要的
也许不着急分类所有事务所，但是中文vup和日语的vtb需要有个快速分类的方法，默认不分类，但是想分类的时候可以分类

**Comment by simon300000** [comment]
这的确是脱了很久的todo啊
不过搞好了vdb，应该是水到渠成...吧
我最近也有点忙，可能不会特别productive→_→

**Comment by wudifeixue** [comment]
没事儿ww 主要想提一下感觉这个功能优先度比较高
