### ISSUE TITLE
在关注历史和舰团变化的表格里加入直播时间段的统计

### ISSUE THREAD

**Issue by Theergold** [dd-center/vtbs.moe#140]
个人认为在关注历史表格内加入直播时间的标注有利于分析直播时段内到底涨了多少粉,还能判断视频投稿能涨多少粉.

**Comment by simon300000** [comment]
咦，有道理

**Comment by Theergold** [comment]
> 咦，有道理

但是好像是直播记录功能没做好的样子?我试了好多都加载不出来

**Comment by simon300000** [comment]
> > 咦，有道理
> 
> 但是好像是直播记录功能没做好的样子?我试了好多都加载不出来

嗯，本来是有个服务器在记录的，结果那个服务器的硬盘炸了，现在还没想好怎么办

**Comment by Theergold** [comment]
> > > 咦，有道理
> > 
> > 
> > 但是好像是直播记录功能没做好的样子？我试了好多都加载不出来
> 
> 嗯，本来是有个服务器在记录的，结果那个服务器的硬盘炸了，现在还没想好怎么办

 是不是我捐赠个服务器就能好起来(笑)

**Comment by simon300000** [comment]
> > > > 咦，有道理
> > > 
> > > 
> > > 但是好像是直播记录功能没做好的样子？我试了好多都加载不出来
> > 
> > 
> > 嗯，本来是有个服务器在记录的，结果那个服务器的硬盘炸了，现在还没想好怎么办
> 
> 是不是我捐赠个服务器就能好起来(笑)

2333 DD@Home

**Comment by Theergold** [comment]
所以这个功能实装了嘛

**Comment by simon300000** [comment]
没→_→

**Comment by Theergold** [comment]
直播记录是没写好还是没服务器啊(没半个月来催一把)
(顺便今天DD@home里面好像有一堆奇奇怪怪的东西,什么回事呢)
[](https://i.loli.net/2020/03/07/rFKEs97OzAanc8k.png)

**Comment by Theergold** [comment]
![](https://i.loli.net/2020/03/07/rFKEs97OzAanc8k.png)

刚刚忘了markdown语法

**Comment by simon300000** [comment]
没写好→_→🐦
那个好多 我叫楠楠 估计是因为他网络情况不好，断了又重新连接，但是服务端以为没有断，所以就出现了很多个www
可能是因为WebSocket的协议需要发一个断掉的包，网络不好的情况下直接断开连接不发送这个包的话服务端就以为一直没有断，我可能需要加一个超时断连的功能

**Comment by Theergold** [comment]
老哥啊,直播记录啥时候能实装啊,有些时候查数据看着空着一栏怪难受的

**Comment by Theergold** [comment]
捞一下大半年钱提的Issues...
