### ISSUE TITLE
网站的图标好难看啊

### ISSUE THREAD

**Issue by zhz1237ok** [dd-center/vtbs.moe#144]
![image](https://user-images.githubusercontent.com/38283893/74585133-76beb880-5014-11ea-97cc-f80fe19f78ea.png)
换成白底黑字或者白底蓝字都比这黄底好看吧...

**Comment by simon300000** [comment]
的确
有道理哎

**Comment by zhz1237ok** [comment]
> 的确
> 有道理哎

https://vtbs.moe/favicon.ico
我这边图标还是黄底的，是不是因为png格式无法变成ico图标的原因还是我没清理图标的缓存

**Comment by simon300000** [comment]
应该是CDN的缓存，我晚点去把那个缓存关闭了吧

**Comment by simon300000** [comment]
调了一下缓存策略，应该好了
