### ISSUE TITLE
需要该网站的社团后台管理

### ISSUE THREAD

**Issue by 8MiYile** [dd-center/vtbs.moe#147]
若能提供的话 感谢大哥啦
意思就是编辑社团成员用的 不影响其他人的

**Comment by simon300000** [comment]
快请 https://github.com/dd-center/vdb/

**Comment by 8MiYile** [comment]
@simon300000 难道没法子提供社团用的后台吗?因为只是不想频繁麻烦你们...

**Comment by simon300000** [comment]
可以通过PullRequest提供（

**Comment by simon300000** [comment]
没有后台管理（摊手）
