### ISSUE TITLE
历史数据里面的archiveView 会在数据中间出现一些0

### ISSUE THREAD

**Issue by caoyu-yiyue** [dd-center/vtbs.moe#153]
从 `https://api.vtbs.moe/v2/bulkActive/:mid` 里获取到的历史数据，里面夹杂着一些突然出现的0，比如 `mid: 2655668`，`time: 1585227720969`，而且情况不算少。这样会给计算日均差，或者截取某一段时间之后再向前补缺失值造成一点儿风险（如果第一天截到了 0 那就没办法向前补确实值了）。

archiveView 应该是只增不降才对，数据中间突然出现的 0 一定是出现什么问题了导致的缺失值吧？

这样的数据能不能在历史数据库里剔除掉呢？爬取的时候遇到 0 不添加到库里，或者重试一次怎么样呢？ 

谢谢～！

**Comment by simon300000** [comment]
谢谢提醒，这个应该是bilibili的问题，我看能不能发现有0就不记录这个数据/重试，应该可以修复这个问题

**Comment by caoyu-yiyue** [comment]
OK~！回复好快！多谢～！

**Comment by caoyu-yiyue** [comment]
对了，我也发现了的确是真的有 0 的情况（新 UP 只直播没有投过稿的），所以大概还得和以前的数据比对一下才能确定是不是真的缺失。

**Comment by simon300000** [comment]
嗯嗯 这也是
