### ISSUE TITLE
8Mi-VtbNews 2020-04-16

### ISSUE THREAD

**Issue by 8MiYile** [dd-center/vtbs.moe#156]
https://github.com/8MiYile/HomoCraftServer/blob/master/lib/8Mi_VtbNews/2020-04-16.md<br>
对于这种事,DD们泥萌咋看???

**Comment by simon300000** [comment]
草，新闻发到这里来了

**Comment by H4M5TER** [comment]
炎上自己b站开专栏 炎到别人issue区啥意思？

**Comment by Afanyiyu** [comment]
GitHub Issues是用来提出改进建议和提交bug反馈的地方。此Issue已关闭。
