### ISSUE TITLE
直播势页面数据与主站直播数据存在差异. 有些直播似乎没有置顶排序显示.

### ISSUE THREAD

**Issue by WangJJ1121** [dd-center/vtbs.moe#157]
同一个时间, 页面也都刷新. 但是vtbs.moe的直播势页面与bilibili主站直播的数据同步似乎有一些问题. 有些直播没有被显示.

![update](https://user-images.githubusercontent.com/39559535/79634320-550cb980-819c-11ea-9f2b-408439bbfd4a.png)

**Comment by simon300000** [comment]
bilibili限制了同时的ws连接，我正在尝试解决这个问题→_→

**Comment by simon300000** [comment]
暂时修复力
https://github.com/dd-center/bilibili-vtuber-live-danmaku-relay/commit/c0f3fe232f94a7db3aa31d76562ddc6edcc78a13
