### ISSUE TITLE
来自一个渴求知识的弱小萌新（关于贴贴页面）

### ISSUE THREAD

**Issue by lxqfeng** [dd-center/vtbs.moe#162]
作者大大，您好啊，我只是一名普通计算机专业的大二学生，发表这个issue只是想单纯向大大请教一个问题（或者说请求），我第一次看到大大的vtbs.moe中的贴贴页面，就勾起了我的兴趣，想自己模仿也弄一个这样类似的页面（实际上是web前端课程设计要求做网页-_-!）,但是奈何本人实力不够，只了解到这应该是用ECharts构建的关系图，昨晚恶补了一下ECharts，但是没有关于具体构建关系图的教程，官网的例程也与大大的那个贴贴页面效果大有不同，因为本人技术实在低下，算是刚接触github的萌新，没有找到大大对那个贴贴页面的具体介绍，所以恳求大大能不能在百忙之中抽出一点点的时间给我邮箱发一份那个 ’贴贴‘页面的具体源码，如果有解析就更好了（渴求知识 0.0），我的邮箱：lxqfeng619@163.com，我只是想模仿出和大大那个贴贴页面一样效果的网页，仅仅满足自己的兴趣和课程设计，因为那个贴贴真的超级棒！不会用做其他用途，会附上大大的vtbs.moe网站链接，希望大大能满足我这个想学习技术但是又很垃圾的菜鸡，再次恳求大大！！！

**Comment by simon300000** [comment]
源码在这

https://github.com/dd-center/vtbs.moe/blob/7def1104b4c40ee8f944d5b9a13641c2b93cac8b/src/components/tietie.vue

用了cytoscape


https://js.cytoscape.org

这一步没有用ECharts 😅

**Comment by lxqfeng** [comment]
谢谢 谢谢啦

**Comment by simon300000** [comment]
应该解决了吧
