### ISSUE TITLE
Tweak: api.vtbs.moe 国内移动线路晚上访问链接速度缓慢，可能是晚上用的人多的缘故

### ISSUE THREAD

**Issue by Neteraxe** [dd-center/vtbs.moe#173]
Waiting(TTFB)=4.28s
Content Download=6.0min
具体情况
<a href="图">https://gitee.com/Neterace/pdf/raw/master/Capture.PNG</a>

**Comment by simon300000** [comment]
这个不是google api吧？

**Comment by simon300000** [comment]
看起来在东京的服务器还是有部分区域访问很慢

**Comment by Neteraxe** [comment]
是storage.googeapis.com/workbox-cdn/releases/_private/fetchWrapper.mjs:111
似乎时快时慢，到晚上就连接比较慢
好多国外资源都有晚上加载速度特别慢的情况
现在好像速度正常了，但是不知道是不是只是白天的缘故
也许也是我因为更改了屏蔽规则

**Comment by simon300000** [comment]
这个应该是通过workbox包了一层的fetch，本质上慢的还是api.vtbs.moe，这个服务器在东京，有些慢慢的

**Comment by Neteraxe** [comment]
原来如此，不懂前端，可以本地缓存或者什么的吗?

**Comment by Neteraxe** [comment]
发现不加载其实也没什么问题，可否用try——catch之类的看情况加载

**Comment by simon300000** [comment]
现在已经有一个简单的本地缓存
<img width="616" alt="image" src="https://user-images.githubusercontent.com/12656264/82775327-acf7a980-9e47-11ea-9e21-61d29a7e2251.png">
显示这个`数据缓存于`的时候就其实是本地缓存中的数据

**Comment by simon300000** [comment]
我现在也在尝试部署一个稍微快一些的服务器（

**Comment by Neteraxe** [comment]
开发者辛苦了!
我看fork了15人但好像只用开发者一人在commit

**Comment by simon300000** [comment]
这主要也是我写的不好看懂www
代码有点乱糟糟的，一开始写的时候还没有做这样的项目的经验，所以规划的就不大好

**Comment by Neteraxe** [comment]
是没有"框架"的问题
<a href>https://github.com/Gaohaoyang/gaohaoyang.github.io</a>
开发者可以看一下这个工程，这个博客网页真的有不少可以学习的地方

**Comment by simon300000** [comment]
是呀，总是要学习的
不过其实还是有人commit的
比如#172 （虽然是认识的人）

**Comment by Neteraxe** [comment]
可否进行本地的一个代理?
脑洞有点大
<a href>https://github.com/joshdick/miniProxy</a>
只需要一个23.4kb的php文件，还可以精简一下

**Comment by simon300000** [comment]
网页端上的代理帮不上忙吧，本机和服务器之间连接很慢，在本地打开代理没有什么帮助吧

**Comment by Neteraxe** [comment]
其实是可以的，这个我试过，是网页端服务器用做客户端的反向代理，但是问题是人多的话会很卡，而且别人可以利用代理链接的漏洞，总之不一定是好主意，而且可能也不合法
当我没说过

**Comment by simon300000** [comment]
不大懂。。。

**Comment by Neteraxe** [comment]
其实就是VPN，不过是网页端的:)

**Comment by simon300000** [comment]
那这还是要连接在东京的服务器啊哈哈
