### ISSUE TITLE
添加ping-pong API（用以测试服务器延迟）

### ISSUE THREAD

**Issue by tinyAdapter** [dd-center/vtbs.moe#174]
目前不是有三个CDN节点嘛，这边想搞一个自动选择最低延迟的节点进行数据请求的系统

但是请求根路径返回的是404，某些带异常处理的Web框架处理这部分逻辑有点麻烦（说的就是你，.NET）

随随便便请求带数据的API但又不用数据的话感觉又不太合适，毕竟占用了服务器资源

所以能不能搞个不涉及任何服务器计算的API（比如 /ping，直接返回200 "pong"），客户端专门用来计算与服务器间的延迟？

**Comment by simon300000** [comment]
okok

**Comment by simon300000** [comment]
我也弄一个返回可用CDN的api吧

**Comment by tinyAdapter** [comment]
> 我也弄一个返回可用CDN的api吧

okok

**Comment by simon300000** [comment]
https://api.vtbs.moe/meta/ping
https://api.vtbs.moe/meta/cdn
https://api.vtbs.moe/meta/timestamp

**Comment by simon300000** [comment]
应该好了吧（
