### ISSUE TITLE
建立Android分支

### ISSUE THREAD

**Issue by Neteraxe** [dd-center/vtbs.moe#175]
Flutter详细了解了一下，是跨平台框架，但是实际已经过气了，现在常用RN框架，这个和Android开发其实没有关系，是单纯的CSS，但移动端跨平台框架都有B级性能问题，觉得纯Android的工作更适合开发

**Comment by Neteraxe** [comment]
而且移动端本来就慢，再用跨平台总觉得问题很大

**Comment by Neteraxe** [comment]
@simon300000

**Comment by simon300000** [comment]
那甚至可以用weex（

**Comment by Neteraxe** [comment]
我又仔细了解了一下Flutter，决定投入Flutter开发，框架其实还是不错的，相比RN和Weex速度快的多，只比原生慢一点点，在可接受范围
