### ISSUE TITLE
建立Gitee镜像

### ISSUE THREAD

**Issue by Neteraxe** [dd-center/vtbs.moe#177]
clone老麻烦了

**Comment by Neteraxe** [comment]
Gitee也可以建立组织

**Comment by Neteraxe** [comment]
镜像自己建过，完全可以
@simon300000

**Comment by Neteraxe** [comment]
而且建议将Gitee分部交给另一个成员维护，这样可以增加项目活性

**Comment by simon300000** [comment]
clone咋了？

**Comment by Neteraxe** [comment]
速度不行，常常只有几十KB，也许作者是在网络特区的缘故所以感觉不到

**Comment by simon300000** [comment]
快请中国移动

**Comment by simon300000** [comment]
可以啊，clone到gitee那边去

**Comment by Neteraxe** [comment]
这样有利于项目的进一步发展，在Gitee建立一个组织通过链接检出就可以，我认为项目作者过于集权，几乎全包办了，Gitee分部让另一个成员负责就好
还有，为什么叫dd-center(:
如果全员都dd，就没人编程了

**Comment by simon300000** [comment]
然后这样带来什么好处呢？

**Comment by Neteraxe** [comment]
可以增加活性，这样觉得

**Comment by Neteraxe** [comment]
不想做DDatFlutter了，不太喜欢DD文化
VtbMusic需要增加移动端吗?可以帮忙，当然还是外部协作者







在 2020-06-03 02:53:01，"simon3000" <notifications@github.com> 写道：

然后这样带来什么好处呢？

**Comment by simon300000** [comment]
这里有个QQ群
392381367
