### ISSUE TITLE
新的粉丝团数据指标

### ISSUE THREAD

**Issue by ZTMC** [dd-center/vtbs.moe#189]
现在直播间已关注的频道会显示一个名为粉丝团的指标, 目测是拥有该主播的粉丝勋章的人数. 这个指标有一定的指导意义, 建议追加该对数据的爬取.

**Comment by simon300000** [comment]
嗯 我去研究一下

simon3000

**Comment by Neteraxe** [comment]
@ZTMC 其实你应该尝试自己去PR，最近我也在研究前端，simon300000的代码水平是比较高的，我用validator竟没有检测出任何错误，而国内很多blog都大量错误满篇。真的，值得敬重

**Comment by simon300000** [comment]
惊（

不过如果要pr的话，要先去 [https://github.com/simon300000/bili-api](https://github.com/simon300000/bili-api) 安排这个爬虫的功能

然后才在这里pr

**Comment by wudifeixue** [comment]
笑死，原来真的鸽了3年的指标...
duplicate #442 #245
