### ISSUE TITLE
定期提供一份所有数据的 dump

### ISSUE THREAD

**Issue by ZeroAurora** [dd-center/vtbs.moe#192]
突然发现这个网站的数据非常有研究价值，所以希望能不能定期提供一份所有数据的 dump(.json.gz 之类的) 发布在某个地方（比如 GitHub 里面），方便数据研究/可视化等等用途qwq
（虽然就算给我这个数据我也多半……咕咕咕咕咕咕咕咕咕x）

**Comment by simon300000** [comment]
https://github.com/dd-center/vtbs.moe/blob/master/api.md#all-active-httpsapivtbsmoev3allactive
嘿嘿 有这个

**Comment by ZeroAurora** [comment]
啊上手试了一下，感觉 buffer 有点难处理，并且包含数据好像有点少（好像就 follower 和 view）
还是希望能够有一份更为完整的数据dump的qwq

**Comment by simon300000** [comment]
的确可以安排一下www

**Comment by ZeroAurora** [comment]
最近在做研究性学习的时候用脚本请求API中的历史数据，但是因为网络等等原因总是无法成功，于是我又来要网站数据了（逃
希望获得的：
1. vtb 的完整数据（相当于 https://api.vtbs.moe/v1/fullInfo）
2. 历史数据（https://api.vtbs.moe/v2/bulkActive/:mid）
3. 如果可以的话，还想要一份历史弹幕数据库（因为 https://github.com/dd-center/bilibili-vtuber-danmaku 太大了 clone 不动
4. （不过因为有 https://matsuri.icu/ 的数据库所以3可以不要（逃

**Comment by simon300000** [comment]
3大概可以用Download ZIP

另外两个我有办法可以把数据库全部弄出来变成json，但是用起来可能比buffer还麻烦
我试试看

**Comment by ZeroAurora** [comment]
其实只要是pandas支持的格式都可以的（）
感谢感谢

**Comment by wudifeixue** [comment]
最近发现有人拿数据去搞一些疑似违法和非常有害他人的事情，提供数据这件事不再变得那么开放
