### ISSUE TITLE
你服务器炸了-__-

### ISSUE THREAD

**Issue by Janet-Baker** [dd-center/vtbs.moe#194]
你服务器vtbs.moe炸了

在`https://vtbs.moe/about`下面的log可以看见一大堆RETRY=_=

![202008051837.png](https://i.loli.net/2020/08/05/wyVZq8YHCbMzpX3.png)

真的不考虑修一下吗？

**Comment by simon300000** [comment]
呜呜呜 马上修

**Comment by simon300000** [comment]
应该在 https://github.com/dd-center/vtbs.moe/commit/709ea54202a3c1b38bfb8b057af710e25db78857 修好啦

**Comment by MiracleXYZ** [comment]
从8月9日晚上8点多（UTC+8）开始更新速度显著放慢，有些数据直接停在了那个时候。
猜测可能是B站上了新的风控系统？目前尚不知道新系统的判断标准是啥，我这边每5秒发送2个查询粉丝数的请求都会被封，直播也被迫停了。

**Comment by wtywtykk** [comment]
两天没更新数据了，网站上显示最后更新是17:50

**Comment by simon300000** [comment]
唔 我有时间就去研究研究怎么办
