### ISSUE TITLE
WebSocket 获取弹幕没有结果诶

### ISSUE THREAD

**Issue by caoyu-yiyue** [dd-center/vtbs.moe#199]
啊抱歉连开了两个issues。

使用获取直播间弹幕的 API，按照例子用下面的代码：

```javaScript
const io = require('socket.io-client')
const socket = io('https://api.vtbs.moe/vds')
socket.emit('join', '876396')
socket.on('danmaku', console.log)
```

应该会打印弹幕信息，但是运行没有反应。刚接触 WebSocket，是我哪里搞错了吗？

另外 API 文档里这部分 https://github.com/dd-center/vtbs.moe/blob/master/api.md#vdsocket 的 `Document:` 后面的链接现在打不开了。

**Comment by simon300000** [comment]
哇 回家了看一下修一修

**Comment by simon300000** [comment]
也可以直接用 https://github.com/simon300000/bilibili-live-ws
嘿嘿

**Comment by caoyu-yiyue** [comment]
还有别的框架呀，好强
我也研究一下这个，嘿嘿

**Comment by simon300000** [comment]
现在应该没有别的问题了吧www
