### ISSUE TITLE
建议：考虑一下换一下探测方式？

### ISSUE THREAD

**Issue by Janet-Baker** [dd-center/vtbs.moe#204]
阿B其实有很多种方法可以批量检测主播是否开播的，比如关注列表。
一个账号最多可以同时关注2000个UP主(不算悄悄关注)，按照现有状况来看，大概2个账号就够用了吧？

默认的长这个样子：
> https://api.live.bilibili.com/xlive/web-ucenter/user/following?page=1&page_size=9

如果大胆一点，改一下呢？
>https://api.live.bilibili.com/xlive/web-ucenter/user/following?page=1&page_size=2000

**Comment by Janet-Baker** [comment]
实际测试一下，page_size被限制最大为10。
但是这也比逐个检测要好很多。

**Comment by simon300000** [comment]
其实开播状态是靠人气判断的，人气是靠WebSocket从Bilibili主动推过来，这个反应速度大概20秒
哈哈，所以前几天网页的爬虫崩溃了之后直播人气状态也没问题（

**Comment by Janet-Baker** [comment]
神奇的方法……有想法

**Comment by simon300000** [comment]
呀哈哈
