### ISSUE TITLE
增加个搜索的功能

### ISSUE THREAD

**Issue by luckyray-fan** [dd-center/vtbs.moe#208]
rt, 希望能有人力加个搜索的功能, 有的时候推的主播比较靠后又想关注的话比较麻烦
- 可以先做个急上升的搜索 _(:з」∠)_

**Comment by luckyray-fan** [comment]
看来没人力的样子, 那我这周末提个 pr 吧

**Comment by simon300000** [comment]
在详细有个很简单的搜索，不知道是不是能满足要求
的确没什么时间，网页也有许多想改善的地方没有找到机会，哈哈

**Comment by luckyray-fan** [comment]
代码里看到了, 挺好的, 没啥问题, 不过这个项目跑起来就花了我一晚上哈哈哈

**Comment by simon300000** [comment]
哇 抱歉
我写了一个 development.md
不过有点简单，不是很完善…
可以说一下遇到了什么问题吗，我看看有没有什么我能做的

**Comment by luckyray-fan** [comment]
node版本要求啥的, 配置二进制镜像,  debug的时候sourcemap映射, 还有vue devtool, 稍后我完善下提个pr吧

**Comment by luckyray-fan** [comment]
![image](https://user-images.githubusercontent.com/38815993/92989240-6963a100-f505-11ea-9a7f-30dfe9bbc0b2.png)
![image](https://user-images.githubusercontent.com/38815993/92989242-73859f80-f505-11ea-89aa-96b7ee37e9f4.png)

**Comment by luckyray-fan** [comment]
目前有啥高优的需求没, 我闲着也是看 v, 不如边听边写代码2333
