### ISSUE TITLE
UI：搜索框样式遮挡

### ISSUE THREAD

**Issue by kagaya85** [dd-center/vtbs.moe#225]
提个样式的小问题
这个搜索框在一定范围的窗口宽度内会遮挡到中间的内容
<img width="437" alt="CleanShot_2020-10-27_at_09 10 12@2x" src="https://user-images.githubusercontent.com/28755005/97244663-3dda1300-1834-11eb-9c64-7b471255027b.png">
<img width="1074" alt="CleanShot_2020-10-27_at_09 13 57@2x" src="https://user-images.githubusercontent.com/28755005/97244888-c062d280-1834-11eb-861a-a1aa4d83e822.png">

**Comment by kagaya85** [comment]
之后提个pr

**Comment by simon300000** [comment]
谢谢提醒，戳@luckyray-fan 😀

**Comment by simon300000** [comment]
#226 修好啦 谢谢！

**Comment by kagaya85** [comment]
😘😋
