### ISSUE TITLE
直播间不在自己号上的有没有解决方式

### ISSUE THREAD

**Issue by HetmesAskalana** [dd-center/vtbs.moe#228]
RT（我就是这样的（雾）），认识的其他人也有这样的

**Comment by simon300000** [comment]
把直播间所属的那个空间号也加进账号列表吧
<img width="730" alt="image" src="https://user-images.githubusercontent.com/12656264/97590271-bbea1580-19fe-11eb-8847-c6ae05fbce3c.png">

就这样多写一个
