### ISSUE TITLE
[Feature Request] 希望在 /dd 页面提供一键查水表功能

### ISSUE THREAD

**Issue by lightpencil** [dd-center/vtbs.moe#256]
希望在 /dd 页面提供一键查水表的前端搜索框功能，通过 ID/用户名 直接查找单项用户，避免翻页下滑查找/手动 API 请求的痛苦。

**Comment by wudifeixue** [comment]
这个功能偏争议性容易吃函，有在其他几个地方讨论过🤔️
#336 
#232
