### ISSUE TITLE
vtbs.moe连接超时

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [dd-center/vtbs.moe#261]
DDTV 2.0.4.8连接不上vtbs，连接超时
![image](https://user-images.githubusercontent.com/44915585/104314748-d2d7d880-5514-11eb-81f6-d07228256e1a.png)
Chrome网页打开vtbs.moe一直正在连接服务器
![image](https://user-images.githubusercontent.com/44915585/104314844-f6028800-5514-11eb-88b7-7f749d2ee122.png)
CMD ping vtbs.moe -t 一直请求超时
![image](https://user-images.githubusercontent.com/44915585/104315067-5b567900-5515-11eb-83ec-87465bcff01a.png)

**Comment by simon300000** [comment]
我也不清楚是怎么回事 哎。。

**Comment by simon300000** [comment]
我要修一修

**Comment by simon300000** [comment]
你是移动网吗？我怀疑移动有点问题，打了一个电话让让他们修一下

**Comment by SaltyFishOnTheSea** [comment]
> 你是移动网吗？我怀疑移动有点问题，打了一个电话让让他们修一下

是移动网，现在DDTV能连上vtbs了，但是延迟在20s~60s（没错，是秒）

**Comment by HelloCard** [comment]
惨 服务器 惨

**Comment by SaltyFishOnTheSea** [comment]
科学工具全局，vtbs服务器延迟在1000ms上下，这是什么魔法

**Comment by SaltyFishOnTheSea** [comment]
PAC改成绕过大陆域名，延迟瞬间回到150ms，看起来是被厦门移动墙了

**Comment by simon300000** [comment]
正在和移动扯皮中…

simon3000
simon30002021@icloud.com

**Comment by wdpm** [comment]
> 正在和移动扯皮中… simon3000 simon30002021@icloud.com
> […](#)
> 在 2021年1月17日，下午11:41，SaltyFishOnTheSea ***@***.***> 写道： ﻿ PAC改成绕过大陆域名，延迟瞬间回到150ms，看起来是被厦门移动墙了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

发生甚么事了。貌似我使用的socket.io的info API不能返回数据了。@simon300000

**Comment by EdwardXiaoran** [comment]
广东移动上不去~~

**Comment by wdpm** [comment]
> 广东移动上不去~~

建议你科学上网。反正移动我也上不去。

**Comment by EdwardXiaoran** [comment]
> > 广东移动上不去~~
> 
> 建议你科学上网。反正移动我也上不去。

我代理是香港的，也上不去

**Comment by wdpm** [comment]
> > > 广东移动上不去~~
> > 
> > 
> > 建议你科学上网。反正移动我也上不去。
> 
> 我代理是香港的，也上不去

vtbs.moe这个网站我能通过代理访问，但是它的API我即使通过代理也搞不定。

**Comment by simon300000** [comment]
移动似乎修好了 api的问题我觉得挺怪的 还要研究研究

**Comment by simon300000** [comment]
我觉得可能是dns的问题 可以试试看 api.tokyo.vtbs.moe

> > 正在和移动扯皮中… simon3000 [simon30002021@icloud.com](mailto:simon30002021@icloud.com)
> > […](#)
> > 在 2021年1月17日，下午11:41，SaltyFishOnTheSea _**@**_.***> 写道： ﻿ PAC改成绕过大陆域名，延迟瞬间回到150ms，看起来是被厦门移动墙了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 发生甚么事了。貌似我使用的socket.io的info API不能返回数据了。@simon300000

**Comment by wdpm** [comment]
tokyo cdn也搞不定。我准备添加http轮询模式和bilibili官网模式了，问题不大。即使你api炸了也可以优雅降级。

**Comment by EdwardXiaoran** [comment]
上面那个已注销账户提及的issue，有点问题，建议移除

**Comment by simon300000** [comment]
每个issue都有，我看看github能不能帮我删咯
