### ISSUE TITLE
现在似乎有些直播间的弹幕没有收集全诶

### ISSUE THREAD

**Issue by luckyray-fan** [dd-center/vtbs.moe#264]
![image](https://user-images.githubusercontent.com/38815993/106350623-7b59ab00-6311-11eb-8772-663528121b85.png)
如上图, 昨天这个房间应该是由10w+弹幕的

**Comment by luckyray-fan** [comment]
[https://github.com/dd-center/bilibili-vtuber-danmaku/blob/fac0530af61c91dac8b37fd8cae85184b78f6b91/22625025/2021-1-29.txt](https://github.com/dd-center/bilibili-vtuber-danmaku/blob/fac0530af61c91dac8b37fd8cae85184b78f6b91/22625025/2021-1-29.txt)
附上链接

**Comment by luckyray-fan** [comment]
看错了🤣

**Comment by simon300000** [comment]
唔
