### ISSUE TITLE
“关于”页面的性能问题

### ISSUE THREAD

**Issue by sjx233** [dd-center/vtbs.moe#266]
https://github.com/dd-center/vtbs.moe/blob/9197b5cbf811a77d3c044a6c4b47a8e824890906/src/store.js#L142-L145

https://github.com/dd-center/vtbs.moe/blob/9197b5cbf811a77d3c044a6c4b47a8e824890906/src/views/About.vue#L115-L117

超限后每个 index 对应的 log 是不断变化的，把 index 作为 key 似乎导致了性能问题（#118）。可以给每条 log 唯一编号作为 key。

**Comment by simon300000** [comment]
好办法
