### ISSUE TITLE
[建议]更换BiliOB观察者链接至BiliOB233，为已宣布毕业的社团和V添加标注

### ISSUE THREAD

**Issue by Tiandians** [dd-center/vtbs.moe#269]
如题：

1. BiliOB早已发布[最终致辞](https://www.biliob.com/)并停止服务，建议将BiliOB观察者方框中的链接更改至由匿名开源社区成员提供的`https://www.biliob233.com/`。
2. 建议为已宣布毕业的社团和V添加状态标注（比如灰色）等，方便搜索
3. 有几处不知道是没有开发还是发生了错误？
    - `detail`页面`直播时长`标签全部显示为NaN
    - 所有`播放量`的统计均显示为0

**Comment by Tiandians** [comment]
再加一个建议：

4. 在Vtuber页面添加已经过官方授权的字幕组的链接

**Comment by simon300000** [comment]
有道理有道理
直播时长坏了，一直没有修www。我准备直接改成别的站的数据
播放量统计为0，因为播放量的那个api现在不能匿名用啦
