### ISSUE TITLE
如何同步vdb数据库到网页后端api

### ISSUE THREAD

**Issue by ghost** [dd-center/vtbs.moe#283]
对大佬的项目仰慕已久，最近搭了一个镜像站用作学习研究

在成功构建并运行前后端后，发现数据库里只有5个V的数据，找不到同步vdb数据库到网站后端的方法

如果大佬有时间的话还希望指点一二，十分感谢

**Comment by simon300000** [comment]
用mock启动的话只有5个，因为mock一般是拿来本地开发，多了爬不过来

试试看把这行代码注释掉 https://github.com/dd-center/vtbs.moe/blob/bda2d8155bb884cd80354632f3712ea1d7131a21/api/mock/index.js#L7

**Comment by simon300000** [comment]
额，似乎完全ghost了
