### ISSUE TITLE
爬虫优化方案

### ISSUE THREAD

**Issue by Chen-Luan** [dd-center/vtbs.moe#296]
可以根据V的日增来推断V是否毕业

大约有2200多的V日增在0±5，占总V数的65%
可以考虑降低这些V的爬取频率，从而节省流量和负载

辛苦啦！

**Comment by simon300000** [comment]
目前已经实施了类似的措施
https://github.com/dd-center/vtbs.moe/commit/f5c2f67cdf51bae15d874146a3bd36b5e38c6773
