### ISSUE TITLE
DD风云榜好几天未更新了

### ISSUE THREAD

**Issue by WencongZuo** [dd-center/vtbs.moe#311]
DD风云榜最近一直没有更新，显示的上次更新是10月29日。
![Screenshot_2021-11-12-10-18-21-707_com android chrome](https://user-images.githubusercontent.com/92371141/141382838-1c057844-155e-4272-8f98-087061411acf.jpg)
请帮忙看一看是不是哪里出问题了，谢谢。

**Comment by simon300000** [comment]
的确看到了这个问题，我研究研究

**Comment by simon300000** [comment]
前几天bilibili改变了api，我进行了一个升级，可能不是很完善

**Comment by Georgehaoren** [comment]
依然显示上次更新10月29号，是出什么问题了么？
谢谢谢谢

**Comment by simon300000** [comment]
这个问题似乎没有再次出现
