### ISSUE TITLE
似乎爬虫被封了？

### ISSUE THREAD

**Issue by noahzark** [dd-center/vtbs.moe#314]
https://vtbs.moe/about
logs 全部都是RETRY
![image](https://user-images.githubusercontent.com/4402804/143405845-d9e1f784-01b6-490e-999a-ced953125fc8.png)

**Comment by lonelyion** [comment]
应该是爬虫的参数更新了，分页大小现在最大是50，这里请求是100
![image](https://user-images.githubusercontent.com/25267689/143680034-aaea9e09-902d-4d80-abd3-e02513d8aaa5.png)

**Comment by simon300000** [comment]
我会去尝试修复这个问题，但是我最近很忙，所以，可能，要过段时间

**Comment by simon300000** [comment]
修好了 感谢@lonelyion
😘
