### ISSUE TITLE
移动网访问缓慢/无法访问

### ISSUE THREAD

**Issue by TremblingMoeNew** [dd-center/vtbs.moe#316]
无限转圈或者干脆提示无法访问，已经好几天了
用联通的手机热点试了一下能上，应该就是移动上不去（）

**Comment by simon300000** [comment]
az 这是我也无法解决的问题 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/12656264/144745437-b9a72edb-496a-445a-b476-d23e740dbe70.png">
要不要考虑选择这个cdn试试（是cloudflare）

**Comment by thouser8** [comment]
https://api.vtbs.moe 
https://api.tokyo.vtbs.moe
https://vtbs.musedash.moe
似乎以上三个节点中国移动都无法访问......

**Comment by simon300000** [comment]
惊 我就是中国移动

**Comment by thouser8** [comment]
> 惊 我就是中国移动

我这边江西移动以及江苏移动校园网都NOT FOUND

**Comment by simon300000** [comment]
如果打开显示是not found 那应该是正常的

**Comment by thouser8** [comment]
> 如果打开显示是not found 那应该是正常的

主要我用的dd monitor，它获取vtb的接口就是https://api.vtbs.moe，然后怎么样都获取不到。。。

**Comment by simon300000** [comment]
啊 居然会这样😱😱😱
我我我 我想个办法

**Comment by thouser8** [comment]
> 啊 居然会这样😱😱😱
> 我我我 我想个办法

😘😘麻烦老哥了

**Comment by simon300000** [comment]
我没办法了😭

**Comment by simon300000** [comment]
不 好像有有点希望

**Comment by simon300000** [comment]
目前情况如何，我进行了一些改进
（虽然后端炸了，但是打开网页应该容易许多）

**Comment by thouser8** [comment]
> 目前情况如何，我进行了一些改进
> （虽然后端炸了，但是打开网页应该容易许多）

yesss！！这边确实能正常刷新出来了，谢谢你😘😘顺便祝老哥新年快乐🥳
