### ISSUE TITLE
【数据请求】详细上舰历史？

### ISSUE THREAD

**Issue by wishforgood** [dd-center/vtbs.moe#317]
大大好，我想做一个每月的大航海名单，方便V来统计礼物信息，请问你有留每个人是什么时候上舰的记录吗？
V名：恋诗夜Koxia
mid：690608690

**Comment by simon300000** [comment]
抱歉 我没有历史名单 我只有当前的名单
而且这个名单似乎出问题了，我这几天要修一修（

**Comment by wishforgood** [comment]
好吧，那我再去别处找找，谢谢及时回复
