### ISSUE TITLE
关于一些已注销账户、已无法访问主页的VTuber

### ISSUE THREAD

**Issue by Tinhone** [dd-center/vtbs.moe#353]
如题，冒昧问一下这几种类型的账号还需要继续由爬虫更新信息吗？这两种情况下数据一般已经无法得到了，感觉会占用爬虫的资源欸

**Comment by simon300000** [comment]
其实这样的账号都在慢慢去掉，也不会占用太多的资源（大概只有百分之几

**Comment by Tinhone** [comment]
感觉可以新建一个文件记录这种账号
<del/>VTuber账号纪念馆<del/>

**Comment by simon300000** [comment]
的确可以😢，还好账号数据就算删除了也有记录

**Comment by simon300000** [comment]
> 我也在想，标记一下inactive，这样在vtbs.moe继续可查，但是不会花任何资源再去更新了

其实就算删掉了直接输入url也是可以查历史数据的

**Comment by wudifeixue** [comment]
草，那没啥问题了，关了
