### ISSUE TITLE
发现有一部分VTuber账号的数据记录在3月8日左右停止

### ISSUE THREAD

**Issue by Tinhone** [dd-center/vtbs.moe#357]
如题，UID487817699，UID1818100，UID521780993，UID432896273，UID13688870，UID624408688，UID10917289等等都有这种情况
关于界面的logs显示，这些账号均在多次RETRY后SKIP RETRY
想问问这种情况是因为什么而导致的🤔

**Comment by wudifeixue** [comment]
确实很奇怪，于是我去调查了下原因：

487817699: 超次元学院（不知道为什么是社团数据，一个文件拥有两个账号）
https://space.bilibili.com/487817699
https://space.bilibili.com/545125460
1818100: 黑井柴的犬舍后院（多个不同平台的账号）
![image](https://user-images.githubusercontent.com/7316929/167958985-5f9fea8b-cc27-4b5f-90a7-c5c6dbb1a26e.png)
521780993:花云燻（多平台账号）
432896273: 星婉Official（并没有多平台，但是一样出错了，很奇怪，在submit.vtbs.moe查询数据倒是会出现loading...可是其他有loading的并不一定出错）
13688870: 华莉丝Wallis（多平台）
624408688: 路人甲official（没有多平台，虚拟主播）
![image](https://user-images.githubusercontent.com/7316929/167959868-0e0e0a77-7e66-4f9a-8fac-73d433b40730.png)
10917289: 魂喵Official（没有多平台，社团）

**Comment by wudifeixue** [comment]
嘿嘿，最有意思的是，这些账号又看了一遍以后，统统都有新数据了，好像访问了一次以后，就又复活开始工作了

**Comment by wudifeixue** [comment]
看了下commit，Simon在拼命更新，没事了

**Comment by wudifeixue** [comment]
原因找到了，b站原来在3月8号更新了api，现在已经修复
https://github.com/simon300000/bili-api/commit/bdb1534ba5479ba39263c3de80c74ac45a022616
https://github.com/dd-center/vtbs.moe/commit/516390226f182b38c33b1757ffc7ac6e368b637b

**Comment by wudifeixue** [comment]
补充下看的方法和剩余数据：
![image](https://user-images.githubusercontent.com/7316929/167965522-61bc593f-3708-4bbd-924f-1a731ce47fbf.png)
