### ISSUE TITLE
关于加密直播间的数据更新

### ISSUE THREAD

**Issue by Tinhone** [dd-center/vtbs.moe#358]
看关于页面的logs时发现有几个账号的RETRY拖延了80秒时间，UID和直播间号分别是：
<p>516780319&nbsp&nbsp&nbsp&nbsp21961965&nbsp&nbsp&nbsp&nbsp樱铃万事屋<p/>
<p>1895683714&nbsp&nbsp&nbsp&nbsp23905455&nbsp&nbsp&nbsp&nbsp量子少年Official<p/>
<p>356354146&nbsp&nbsp&nbsp&nbsp22093906&nbsp&nbsp&nbsp&nbsp阿枕如是说道<p/>
<p>1912415960&nbsp&nbsp&nbsp&nbsp22601170&nbsp&nbsp&nbsp&nbsp歌音Utane<p/>
<p>这些账号的直播间均为加密直播间，有没有可能通过打tag的方式来减少加密直播间的数据更新频率？<p/>
<p>可通过返回的错误代码（19002005）或错误消息来判断是否添加或者删除tag<p/>

**Comment by simon300000** [comment]
谢谢提醒 会对这些比较少见的例子进行一些适配

**Comment by wudifeixue** [comment]
目前比较暴力的办法是把这些数据都删了...
