### ISSUE TITLE
想询问一下非“关于”页面为何也会有log的传输连接

### ISSUE THREAD

**Issue by Tinhone** [dd-center/vtbs.moe#382]
如图，在并不是“关于”页面的时候同样会有这个传输连接，故想问问在非“关于”页面添加这个传输连接的原因
![图片](https://user-images.githubusercontent.com/81268244/181533885-4f2846b4-b12d-4537-b165-14c5689b5360.png)

**Comment by simon300000** [comment]
因为我2年前写的程序还有些…可以改进的地方
是正常的，请不用担心
