### ISSUE TITLE
[Feature Request] 希望DD风云榜能够提供可以直接调用的接口

### ISSUE THREAD

**Issue by Megghy** [dd-center/vtbs.moe#385]

**Comment by simon300000** [comment]
哦天哪 抱歉

**Comment by simon300000** [comment]
你好 其实已经有了
https://api.vtbs.moe/v1/guard/all
这个应该是你要找的

**Comment by Megghy** [comment]
原来这个是dd的上了哪些舰而不是v有哪些舰长吗 私密马赛

**Comment by simon300000** [comment]
把后面的all换成id就是v有哪些舰长
https://api.vtbs.moe/v1/guard/:mid

比如yousa
https://api.vtbs.moe/v1/guard/282994

**Comment by Megghy** [comment]
收到收到
