### ISSUE TITLE
修复下vtbs.moe的biliob的链接到新的地方？

### ISSUE THREAD

**Issue by wudifeixue** [dd-center/vtbs.moe#389]
从旧的格式：
https://www.biliob233.com/author/xxxxx
到
https://zeroroku.com/bilibili/author/xxxxx

@simon300000 @Jannchie 觉得如何？

**Comment by simon300000** [comment]
看起来已经在 https://github.com/dd-center/vtbs.moe/commit/a1a294276510024994afcc8002f31afceb3ee8db 解决

**Comment by wudifeixue** [comment]
Ok
