### ISSUE TITLE
打开vtbs.moe收到巨大的推送轰炸严重损害了手机用户体验

### ISSUE THREAD

**Issue by wudifeixue** [dd-center/vtbs.moe#390]
## 如图
![JAH%4B`E9BXACC5{)4 G7D0](https://user-images.githubusercontent.com/7316929/187082190-1c25a714-d6fd-4a75-b5ce-0f164ebef470.png)

这个问题需要尽快解决下，应该是最近这周合并过滤造inactive账户造成的bug，推送也一起跟着延迟了，在打开vtbs.moe的时候会疯狂的推送轰炸很久才结束

**Comment by wudifeixue** [comment]
应该是受到了这个影响，用户流失的比较严重，目前高峰期在线也只有29-30人了

**Comment by wudifeixue** [comment]
解决办法
1. 回滚最近的更新
2. 默认禁止开播提醒，增加手动开启，或者干脆删除此功能（甚至可以大幅度减少ws连接?）

**Comment by simon300000** [comment]
这就删了😠

**Comment by simon300000** [comment]
已经删了🎉

**Comment by wudifeixue** [comment]
ok，以后有恢复的打算吗？换成可用户自己勾选的？

**Comment by simon300000** [comment]
> ok，以后有恢复的打算吗？换成可用户自己勾选的？

可以以后改成勾选吧，（其实现在好像就有这个功能来着）

**Comment by wudifeixue** [comment]
勾选是弹幕么？那个我试了试并没有效果呀

**Comment by simon300000** [comment]
> 勾选是弹幕么？那个我试了试并没有效果呀

hh确实没什么效果（需要进行一些工作

**Comment by wudifeixue** [comment]
已经砍掉了此功能解决了问题
