### ISSUE TITLE
排序榜数据出现严重错误，停留在8月23日左右

### ISSUE THREAD

**Issue by wudifeixue** [dd-center/vtbs.moe#392]
## 错误示例，虚拟小萨已经216,424粉丝，却停留在195,739

![image](https://user-images.githubusercontent.com/7316929/187487323-70e22142-b779-4b08-b8db-67f6649ec39f.png)
![image](https://user-images.githubusercontent.com/7316929/187487290-a937b3ed-fa13-4fec-8008-c2728db8505b.png)
https://vtbs.moe/detail/6415072

此问题已经在各大榜单均已发现，怀疑错误原因来源于一周前的重大更新

## 并且缓存数据也出现严重奇葩现象，我在清理缓存的时候发现了50G的缓存
![2YJULPHU{5EKAHG1$V347RJ](https://user-images.githubusercontent.com/7316929/187487817-17819fbb-81dd-4549-8b8e-8f9360a98cc3.png)

**Comment by wudifeixue** [comment]
初步观察这个bug的特性是会在没有开播的人上体现出来，如果开播的话榜单数据正常

**Comment by wudifeixue** [comment]
进一步观察，如果网站打开超过5分钟以上，等一轮循环结束后，将会得到数据更新，但是不管以前的老缓存，还是新的浏览器用无痕模式重新打开，都会出现错误的数据。

## 等待5分钟后的正确数据：
![image](https://user-images.githubusercontent.com/7316929/187491008-bce4ec45-e912-4afa-9ae0-e6c1e2880cc4.png)



## 错误对比：
![image](https://user-images.githubusercontent.com/7316929/187490916-1f2e3674-9456-49a6-b777-5b78501595fc.png)

**Comment by wudifeixue** [comment]
如果关闭浏览器，这个问题哪怕有5分钟填充了数据修复好了，又会再次回到一开始的样子。
还是尽快修吧，不然每次打开vtbs.moe 5分钟才能有正确数据

**Comment by simon300000** [comment]
已经初步修复
希望这次正常！
