### ISSUE TITLE
[你站炸了] vtbs.moe上的的大量数据仍停留在2022年9月28日05:00 UTC+8

### ISSUE THREAD

**Issue by InterestingFred** [dd-center/vtbs.moe#406]
![图片](https://user-images.githubusercontent.com/106480847/193059375-5d794e84-e4c1-46d6-a156-58a4b06e4f2a.png)

**Comment by Radekyspec** [comment]
由于B站给 https://api.bilibili.com/x/space/acc/info?mid= 这个接口上了验证，之前所有爬取数据的 [DDatHome](https://github.com/dd-center/DDatHome-nodejs) 以及依赖此仓库的[DDatElectron客户端](https://github.com/dd-center/DDatElectron) 全部无法返回正常数据

该问题已经在[DDatHome](https://github.com/dd-center/DDatHome-nodejs)的 [最新commit](https://github.com/dd-center/DDatHome-nodejs/commit/f931714bfbbfe68b21841f623d815e4753104394) 和[DDatHome-python](https://github.com/Radekyspec/DDatHome-python)的 [最新coommit](https://github.com/Radekyspec/DDatHome-python/commit/205a016a34655ffaf71541293f938d2a91876cb3) 中被修复，等之后发布新版本Release即可解决

**Comment by simon300000** [comment]
目前DDatHome和DDatElectron的新版本已经推送

**Comment by simon300000** [comment]
DD@Browser 也有了一个新版本

**Comment by wudifeixue** [comment]
@CHKZL 不知道ddtv那边是否也会受到影响？要不要也更新下

**Comment by Radekyspec** [comment]
> @CHKZL 不知道ddtv那边是否也会受到影响？要不要也更新下

DDTV的应该没有问题，我试过了他们用的Header，没看到有出现-401

**Comment by CHKZL** [comment]
> @CHKZL 不知道ddtv那边是否也会受到影响？要不要也更新下

DDTV没用使用Browser里面的请求方法，是另外自己实现的轮子，并且携带了登录态的，应该不会受到这次修改的影响
