### ISSUE TITLE
希望能够为主页增加翻页模式

### ISSUE THREAD

**Issue by Tinhone** [dd-center/vtbs.moe#409]
目前使用低性能设备在主页上滚动时，很容易出现卡顿和显示问题。因此希望作者大大能够添加一个翻页模式以减少滚动时的卡顿。如果每页显示的vtb能够自定义就更好了！

感谢作者大大！辛苦了！

**Comment by wudifeixue** [comment]
应该只是今天访问的人太多了给卡爆了吧（我看一直300+同时在线）...翻页在当初收录过百条的时候就做了，如果到现在4000多人才做那可能会卡的你根本就打不开首页..哈哈

**Comment by simon300000** [comment]
收到

**Comment by Tinhone** [comment]
> 应该只是今天访问的人太多了给卡爆了吧（我看一直300+同时在线）...翻页在当初收录过百条的时候就做了，如果到现在4000多人才做那可能会卡的你根本就打不开首页..哈哈

我这里翻起来不管有没有联网都会有些卡顿，可能是我的问题吧 ;w;
