### ISSUE TITLE
关于在Chrome和edge浏览器发现无法运行的问题

### ISSUE THREAD

**Issue by Georgebillion** [dd-center/vtbs.moe#457]
时间：2023.9.7
所使用的电脑环境：Windows 10 22H2 19045.2846 
复现issues所使用的浏览器：Chrome 114.0.5735.199/Microsoft Edge 114.0.1823.67+watt toolkits（该工具仅用于绕过SNI访问github和相关网址使用，并不涉及到本网站）
所发现issues的网址：vtbs.moe及其下属所有分支网址
故障描述：今日14:45，本人通过Chrome访问vtbs.moe发现其网站一直卡在了正在连接服务器的状态下，且无法搜索任何vtuber的详细信息；遂换用Edge浏览器，发现故障依旧；于是调用浏览器自身的开发者工具（F12），发现发送的包全部502，通过网页检查发现弹出了noscript标签，内容显示本浏览器未启用JS功能，但经过浏览器设置查询，包括使用[Chrome://](chrome://settings/content/javascript)查询后得知，功能已开启，故实在不明白为啥能加载不正常，后续会贴图描述相关故障。
![image](https://github.com/dd-center/vtbs.moe/assets/40432824/d2a4e0de-b74a-405c-984e-ab7cd2fa6844)
![image](https://github.com/dd-center/vtbs.moe/assets/40432824/a629e615-6db5-49aa-8dae-0911f4b0d418)

**Comment by Georgebillion** [comment]
@simon300000

**Comment by simon300000** [comment]
应该是网站出bug了，现在修好了

**Comment by simon300000** [comment]
应该好了，哎好奇怪

**Comment by wudifeixue** [comment]
应该是好了，我无法复现
