### ISSUE TITLE
【新功能】快捷键唤醒搜索，增强搜索结果文本高亮

### ISSUE THREAD

**Issue by ssoda01** [dd-center/vtbs.moe#463]
作为一个习惯性ctrl+f的人 觉得可以把搜索快捷键和搜索框高亮关联起来
但是屏蔽原生浏览器搜索框之后，又没有文本高亮

于是写了一些更新

**Comment by wudifeixue** [comment]
想法不错，但是不太认同屏蔽默认检索，在pr那边提了下我的建议：https://github.com/dd-center/vtbs.moe/pull/464#issuecomment-1982028615

**Comment by wudifeixue** [comment]
![QQ_1729773161206](https://github.com/user-attachments/assets/c3ee5819-267c-4782-9b6a-521a424f5a8e)
https://developer.apple.com/documentation/
感觉以后也可以参考下苹果这个体验
