### ISSUE TITLE
过滤一下词云来增强使用体验

### ISSUE THREAD

**Issue by wudifeixue** [dd-center/vtbs.moe#62]
由于24小时bot一直有几个关键词，刷的量还是挺大的，总体来讲没有意义。

过滤关键词：
- 点歌
- 角色
- 整理
- 辣条

归类同一类词汇避免分散重复出现：
- 888888888
- 23333
- 66666
- hhhhh

**Comment by simon300000** [comment]
好，我想办法直接通过过滤弹幕的形式来解决

**Comment by simon300000** [comment]
在 https://github.com/bilibili-dd-center/vtbs.moe/commit/fb28f0e78f49fd81c884a30df135004e28845497 加了一点过滤，可以过24小时后看看效果了→_→

**Comment by simon300000** [comment]
按错了
草

**Comment by simon300000** [comment]
似乎要过滤一下哈哈哈哈弹幕？
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/12656264/61593039-bd614700-abda-11e9-9ae2-89bbf605428c.png">

**Comment by wudifeixue** [comment]
哦对
哈哈哈  
啊啊啊  
wwwwww
也可以整理成统一的数据

**Comment by wudifeixue** [comment]
我发现有个问题啊，
888888  
666
hhh  
23333  
怎么都消失了？你这是替换掉了吗？  
理想状态是他们都显示，但是不会显示太多不一样的种类啦  
![image](https://user-images.githubusercontent.com/7316929/61597864-ac143c80-abd2-11e9-933d-b394e9630480.png)
