### ISSUE TITLE
写上不同url

### ISSUE THREAD

**Issue by simon300000** [dd-center/vtbs.moe#93]
把url全写上
master
tokyo等等

**Comment by 8MiYile** [comment]
Tokyo是什么鬼 不应该是写Japan吗

**Comment by simon300000** [comment]
服务器在日本的东京呀
而且这个其实是完成了www

**Comment by simon300000** [comment]
closed in https://github.com/dd-center/vtbs.moe/commit/040a955ff762f50efc87061bff9d1bab21c6805d
